# Cursor Bite — Default Configuration
# ============================================================
# This file defines ALL available configuration keys, their types,
# default values, and descriptions.
# User settings in config.json override these defaults.
# Do NOT edit this file for user customization — edit config.json instead.

from dataclasses import dataclass, field
from typing import Optional


# ── Hotkey Configuration ────────────────────────────────────────────

HOTKEY_MAIN = "Ctrl+Alt+B"
"""Primary activation hotkey. Format: Modifier+Modifier+Key
Supported modifiers: Ctrl, Alt, Shift, Win
Examples: "Ctrl+Alt+B", "Ctrl+Shift+T", "Win+C" """


# ── Translation Configuration ───────────────────────────────────────

TRANSLATION_DEFAULT_TARGET = "en"
"""Default target language code (ISO 639-1).
Common values: en, es, fr, de, zh, hi, ja, ko, pt, ru, ar"""

TRANSLATION_AUTO_DETECT_SOURCE = True
"""Automatically detect the source language of selected text."""

TRANSLATION_OFFLINE_ONLY = False
"""When True, only use offline translation (Argos). No cloud fallback."""


# ── AI Configuration ────────────────────────────────────────────────

AI_ENABLED = True
"""Enable AI-powered features (Explain, Summarize, Rewrite, Ask AI)."""

AI_MODEL = "llama3.2"
"""Default Ollama model name.
Common options: llama3.2, phi3.5, tinyllama, mistral, qwen2.5"""

AI_TEMPERATURE = 0.7
"""Sampling temperature for AI generation (0.0 to 1.0).
Lower = more deterministic. Higher = more creative."""

AI_TIMEOUT_SECONDS = 30
"""Maximum time to wait for an AI response before timing out."""


# ── Privacy Configuration ───────────────────────────────────────────

PRIVACY_OFFLINE_MODE = False
"""When True: no external API calls, no cloud services, fully offline."""

PRIVACY_NO_DATA_RETENTION = True
"""Do not store captured text, prompts, or results persistently."""

PRIVACY_CLIPBOARD_PROTECTION = True
"""Restore original clipboard content after text extraction."""

PRIVACY_SCREENSHOT_RETENTION = False
"""Do not save screenshots to disk. Process in memory only."""

PRIVACY_SENSITIVE_DATA_PROTECTION = True
"""Detect and block sensitive data (emails, phones, keys, etc.) from
being sent to external services."""

PRIVACY_EXTERNAL_PROCESSING_WARNING = True
"""Show a warning when an action requires external processing."""


# ── UI Configuration ────────────────────────────────────────────────

UI_MENU_SIZE = 180
"""Radial menu diameter in pixels."""

UI_ANIMATION_SPEED = 150
"""Animation duration in milliseconds.
Lower = faster, Higher = slower."""

UI_OPACITY = 0.95
"""Menu opacity (0.0 to 1.0).
1.0 = fully opaque, 0.0 = fully transparent."""

UI_POSITION_BEHAVIOR = "smart"
"""How the menu positions itself relative to cursor.
Options: "smart" (auto-reposition near edges),
         "fixed" (always center on cursor),
         "offset" (use a fixed offset from cursor)"""


# ── General Configuration ───────────────────────────────────────────

GENERAL_START_WITH_WINDOWS = False
"""Start Cursor Bite automatically when Windows boots."""

GENERAL_ENABLED = True
"""Master enable/disable switch for Cursor Bite."""

GENERAL_ANIMATIONS = True
"""Enable UI animations (fade in/out, hover effects)."""
